/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:1b686af9-71a2-431c-bab7-efa5fe5e65c2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_93pLWArGF",
    "aws_user_pools_web_client_id": "12vk36qaisi4m40em0tcbjcn4q",
    "oauth": {}
};


export default awsmobile;
